// <auto-generated />
using System;
using FamilyPromiseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPromiseApp.Migrations
{
    [DbContext(typeof(FamilyPContext))]
    [Migration("20231204215140_AddColumn")]
    partial class AddColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("FamilyPromiseApp.Models.Case", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentSituation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomesticViolenceHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthChallenge")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsEmployed")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsHoused")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Substance")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakenBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportMethod")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Case", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdultAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdultCellPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdultDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdultWorkPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhone")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChildDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<int?>("HouseHoldChildrenExist")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HouseHoldMemberExist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseHoldNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Referral", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Referral", (string)null);
                });

            modelBuilder.Entity("FamilyPromiseApp.Models.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Resource", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
